language: node_js

node_js:
  - 8

install:
  - npm install

before_script:
  - psql -c "CREATE DATABASE parcels_db_test;" -U postgres

script:
  - npm test

env:
  global:
    - NODE_ENV=test
    - JWT_SECRET_KEY=hfjkds

services:
  - postgresql