language: node_js

node_js:
  - 8

services:
  - postgresql

install:
  - npm install

before_install:
  - psql -c "CREATE DATABASE parcels_db_test;" -U postgres

script:
  - npm test

env:
  global:
    - NODE_ENV=test
    - JWT_SECRET_KEY=anything_secure